import "../scss/main.scss";
import "../static/favicon.png";
import "../static/logo-dark.png";
import "../font/Playfair_Display/PlayfairDisplay-Regular.ttf"
import "../font/Dosis/Dosis-Regular.ttf";
import "../font/Montserrat/Montserrat-Regular.ttf";
import "../img/1.jpg";
import "../img/2.jpg";
import "../img/3.jpg";
import "../img/4.jpg";
import "../img/5.jpg";
import "../img/6.jpg";
import "../img/7.jpg";
import "../img/8.jpg";
import "../img/9.jpg";
import "../img/10.jpg";
import "../img/11.jpg";
import "../img/12.jpg";
import "../img/13.jpg";
import "../img/14.jpg";
import "../img/15.jpg";

import "./grid/MasonryGrid";